# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

#read more on this at https://github.com/neoforged/ModDevGradle?tab=readme-ov-file#better-minecraft-parameter-names--javadoc-parchment
# you can also find the latest versions at: https://parchmentmc.org/docs/getting-started
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
# Environment Properties
# You can find the latest versions here: https://projects.neoforged.net/neoforged/neoforge
# The Minecraft version must agree with the Neo version to get a valid artifact
minecraft_version=1.21.1
# The Minecraft version range can use any release version of Minecraft as bounds.
# Snapshots, pre-releases, and release candidates are not guaranteed to sort properly
# as they do not follow standard versioning conventions.
minecraft_version_range=[1.21.1]
# The Neo version must agree with the Minecraft version to get a valid artifact
neo_version=21.1.228
# The loader version range can only use the major version of FML as bounds
loader_version_range=[1,)

## Mod Properties

# The unique mod identifier for the mod. Must be lowercase in English locale. Must fit the regex [a-z][a-z0-9_]{1,63}
# Must match the String constant located in the main mod class annotated with @Mod.
mod_id=mythicmetals
# The human-readable display name for the mod.
mod_name=Mythic Metals
# The license of the mod. Review your options at https://choosealicense.com/. All Rights Reserved is the default.
mod_license=MIT
# The group ID for the mod. It is only important when publishing as an artifact to a Maven repository.
# This should match the base package used for the mod sources.
# See https://maven.apache.org/guides/mini/guide-naming-conventions.html
mod_group_id=com.mythicmetals

# Mod Properties
mod_version = 0.24.5+1.21
maven_group = com.mythicmetals
archives_base_name = mythicmetals

# Fabric
loader_version=0.16.13
fabric_version=0.115.4+1.21.1

# Dependencies
cca_version=6.1.0
# https://maven.terraformersmc.com/releases/com/terraformersmc/modmenu/
modmenu_version=11.0.1
# https://modrinth.com/mod/alloy-forgery
alloyforgery_version=2.4.1+1.21
# https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items/files/
# https://maven.shedaniel.me/me/shedaniel/RoughlyEnoughItems-fabric/
rei_version=16.0.729
# https://modrinth.com/mod/architectury-api
architectury_version=13.0.2
# OwO
# https://maven.wispforest.io/#/releases/io/wispforest/owo-lib/
owo_version=0.12.14-beta.1+1.21
endec_version=0.1.1
# https://modrinth.com/mod/isometric-renders
isorender_version=0.4.7+1.21
worldmesher_version=0.4.6+1.21
# Apoli and Calio for Origins compat
# https://github.com/apace100/apoli
# https://github.com/EdwinMindcraft/origins-forge/tree/1.21.x/neo
apoli_version=1.21.x~neo-SNAPSHOT
calio_version=1.21.x~neo-SNAPSHOT
# Mythic Metals - Decorations
mmdecorations_version=0.5.2
# Additional Entity Attributes
# https://modrinth.com/mod/additionalentityattributes/
aea_versionite=2.0.2+1.21.1-neoforge
# Common Protection API
# https://maven.nucleoid.xyz/eu/pb4/common-protection-api/
cpa_version = 1.0.0
# EMI
# https://github.com/emilyploszaj/emi
emi_version=1.1.10+1.21
# Explosive Enhancement
# https://modrinth.com/mod/explosive-enhancement
ee_version=1.1.2
# https://maven.enjarai.dev/#/releases/nl/enjarai/cicada-lib
cicada_version=0.13.1+1.21-1.21.1
forgified_fabric_api_version=0.116.7+2.2.4+1.21.1
forgified_fabric_loader_version=2.5.24+0.15.10+1.21